### ISSUE TITLE
Numkeys and Numpad enhancements

### ISSUE THREAD

**Issue by EdLichtman** [jayanam/shortcut_VUr#1]
Hi Jayanam,

I like this addon a lot, it's very helpful! I was wondering if you're planning the feature of Number Key and Numpad detection?

**Comment by jayanam** [comment]
Hi @EdLichtman, yes will add number keys soon, sorry for late reply.

**Comment by Blenux** [comment]
I assume this is for the standard number keys too, has I was about to write the same issue (edit mode, changing from vertices's to edge to face etc).

Otherwise great new update compared to the old screencast addon, so thanks!.

2.8 FTW!

**Comment by EdLichtman** [comment]
@jayanam no problem. I was looking at the code myself a little while ago and I noticed you wrote out each "Acceptable Key". I'm curious if you've looked into Regex or else if you have a specific reason not to use Regex for this purpose?

**Comment by jayanam** [comment]
@EdLichtman : No, just knew that I had to revert the logic anyway so I started with a simple approach. Now I let all keys pass except special ones.
