### ISSUE TITLE
Screen Recorder not showing text on resize

### ISSUE THREAD

**Issue by Tdledbetter** [jayanam/shortcut_VUr#10]
When resizing an object the screen casting tools do not display the values being resized to.  IE:  If I press [R] [x] 1.5  nothing will display other than the R and X.

**Comment by jayanam** [comment]
Yes, this is due to the modifier concept of Blender, so the keystrokes while a modifier is active, are not sent anymore to the VUr addon.

**Comment by ldo** [comment]
Seems like a Blender-specific addon is always going to be subject to limitations in the way Blender lets it work. For example, you might want to show keystrokes elsewhere than in the 3D viewport.

Better to use something like [key-mon](https://github.com/ldo/key-mon/), which is not tied to Blender at all, and will work in any app.
