### ISSUE TITLE
The Shortcut VUr does not capture (display) the ESC key

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/shortcut_VUr#14]
If I press the **ESC** key, it does not appear in the VUr display. 
Pressing the **ESC** key is part of some command sequence (e.g. E, ESC, S).
Therefore, the ESC key should be displayed like any other key.

Reporting for Windows 10 Home, 64 bit

Blender version: 2.82 (sub 6), branch: master, commit date: 2019-12-25 23:32, hash: fa5e28ab08c7, type: Release build date: 2019-12-26, 00:05:50

VUr version: 2.7.3
Python: 3.7.4

**Comment by jayanam** [comment]
I just tried it and it works, did you use the latest version of the addon?
