### ISSUE TITLE
Toolbar/sidebar covers the shortcuts

### ISSUE THREAD

**Issue by venomgfx** [jayanam/shortcut_VUr#19]
The overlay gets covered by the toolbar/sidebar.

It seems that the position is calculated from the whole editor and not taking into account the toolbar/sidebar regions.

**Comment by jayanam** [comment]
Alright Pablo, will have a look

**Comment by jayanam** [comment]
Let's discuss this a bit. At the moment you can dock the display to the right, left, center or attach it to the cursor, When attaching to the cursor you have options to offset for x and y direction:

![image](https://user-images.githubusercontent.com/18039584/76340852-86bc7600-62fc-11ea-9435-2b36194502dd.png)

Would it be a good option to be able to set the offset for x and y when it is docked to left, right or center as well?

**Comment by venomgfx** [comment]
> Would it be a good option to be able to set the offset for x and y when it is docked to left, right or center as well?

Yes!

_Fun fact, I added that feature to the original Screencast Keys add-on :D_

**Comment by jayanam** [comment]
Haha... really, didn't know that. Ok, will be added ASAP:-)

**Comment by jayanam** [comment]
Alright, implemented. Please check the latest version 0.9.2.0

**Comment by venomgfx** [comment]
Awesome! Will check. I symlinked the cloned the repo in my add-ons folder so it's easy to upgrade :D cheers!
