### ISSUE TITLE
Placement

### ISSUE THREAD

**Issue by callimero** [jayanam/shortcut_VUr#2]
Hi Carsten here!

The placement of the shown keypresses (and mouse now, thanks!) should be editable, I think with the redo/tools window now on the left bottom corner they often get blocked.

Cheers,
Carsten

**Comment by enzyme69** [comment]
<img width="264" alt="screen shot 2018-12-08 at 9 06 05 am" src="https://user-images.githubusercontent.com/3952687/49675155-8d8c8580-fac8-11e8-933e-8cb7fd0816b2.png">

I can confirm this. Need option to make it larger and place it anywhere in 2D view layout.

**Comment by jayanam** [comment]
@callimero @enzyme69 Thx for the input, just working on this.

1h later: Ok, first version of this change added, I set the placement now so that it wont overlap with the tools.
![image](https://user-images.githubusercontent.com/18039584/49685246-a4d76d00-fae0-11e8-8c4f-2b44dcfd58c3.png)

**Comment by callimero** [comment]
I think 2.80 beta changes a bit there again... Now the redo popup floats left and so again.

And the toolbar also hides when the screen resolution is low or GUI scale is high.

Please support a right/lower corner placement or user configurable placement.

![2](https://user-images.githubusercontent.com/7713008/53635695-33f6ab80-3c1e-11e9-8fec-66c606818cb9.png)
![1](https://user-images.githubusercontent.com/7713008/53635684-2b9e7080-3c1e-11e9-8f43-33759c8fa190.png)

**Comment by jayanam** [comment]
Thx, will do

**Comment by jayanam** [comment]
Implemented docking to left or right : https://youtu.be/3pv8Q9wPWUo
