### ISSUE TITLE
Feature request: Improved "heads-up" display for mouse actions (clicks/mousewheel actions)

### ISSUE THREAD

**Issue by raindropsfromsky** [jayanam/shortcut_VUr#3]
Thanks for providing **shortcut_VUr**, as Blender 2.8 does not have a built-in facility.

Unfortunately, it shows small visual clues away from the actual action. 
We have to look at two different locations at once.

In your video titled **Modeling Spin Tool and Boolean**, the OSD indications are superb: 

1. The mouse gestures are attached to the mouse pointer, so easy to make out without having to look at the corner of the screen.
2. The keystrokes are shown with large letters, and Shift is replaced with actual arrow symbol. Again, easy to understand with our peripheral vision (no need to look in corner of screen).

Can you please implement that scheme in the addon?
(alternatively, make it user-selectable option)

Thanks in advance!

**Comment by jayanam** [comment]
Ok, will have a look at this

**Comment by jayanam** [comment]
Added to version 0.9.1.0
