### ISSUE TITLE
Double pressed keys are not recognized

### ISSUE THREAD

**Issue by Leevy27** [jayanam/shortcut_VUr#7]
Hi Jayanam,
In the latest version the tool is not recording key which are pressed twice, like GG or AA. It is only displaying once the keypressed.
Any chance to correct this? Waiting for a range of milli seconds if the key was pressed twice or more times?

**Comment by jayanam** [comment]
It is not in the latest version, it has never been like that. This is why
there is no "correct", what you want is a new feature:-)

**Comment by Leevy27** [comment]
Hi Jayanam,
Thank you for your reply! Much appreciated.
The let me ask in a different manner: is this feature foreseen? It would make sense for me to have such a function in a screencast tool for teaching purposes, or not?

Thank you for your time invested for such agreat tool! Amazing!

**Comment by jayanam** [comment]
Hi, yes I have it in my analyze list.

**Comment by jayanam** [comment]
Ok, it is implemented
