### ISSUE TITLE
Some actions are not identified

### ISSUE THREAD

**Issue by Almaz** [jayanam/shortcut_VUr#8]
If I want to move some vertices 1 meter along the X-axis, I press G, X, 1.
But the indicator only shows G.

**Comment by Leevy27** [comment]
This is true. It is happening on all subsequent command. Extruding with E and constraining the path with Z, E is displayed in the Screencastkey but the Z will not be displayed. Rotate and then pressing Z, the Z is also not displayed, same for Scale and all the others.

**Comment by jayanam** [comment]
This is not possible because when G (or other transform operator) is in
use, the key events are not transferred anymore.
