### ISSUE TITLE
Docking in the middle of the viewport

### ISSUE THREAD

**Issue by Leevy27** [jayanam/shortcut_VUr#9]
Hi Jayanam,
It is a huge work to implement the possibility to dock the Screencastkey in the middle of the 3D Viewport. In the left the settings box is hiding the keys, in the right corner if you have some utilities which are taking the place the whole way to the bottom, the keys are also hidden. In the middle of the viewport it would be the better place. Or having the possibility to place wherever I want on the viewport.

**Comment by jayanam** [comment]
I have this on my list, thx

**Comment by jayanam** [comment]
Fixed in 0.7.0.1
